// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coursesSystem.Models;

namespace coursesSystem.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211019122654_fixedInitial")]
    partial class fixedInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("coursesSystem.Models.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("courseEndAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("courseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("courseStartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("courseId");

                    b.ToTable("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
